version: 2
jobs:
  build:
    docker:
      - image: namachan10777/procon29:latest
    working_directory: /ci
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dep-{{ checksum "./gui/package.json" }}-{{ checksum "./editor/package.json" }}-{{ checksum "./server/dub.selections.json" }}-{{ checksum "./solver/dub.selections.json" }}
      - run:
          name: GUI build
          command: bash ./gui/test.sh
      - run:
          name: Editor build
          command: bash ./editor/test.sh
      - run:
          name: Server test
          command: bash ./server/test.sh
      - run:
          name: Solver test
          command: bash ./solver/test.sh
      - save_cache:
          paths:
            - "./gui/node_modules"
            - "./editor/node_modules"
            - "~/.dub"
          key: v2-dep-{{ checksum "./gui/package.json" }}-{{ checksum "./editor/package.json" }}-{{ checksum "./server/dub.selections.json" }}-{{ checksum "./solver/dub.selections.json" }}
